# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-08 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphinxsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SphinxConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_dir', models.CharField(max_length=256)),
            ],
        ),
    ]
