# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-25 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphinxsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('ios', 'iOS'), ('android', 'Android'), ('3d', '3D')], max_length=32, null=True),
        ),
    ]
