# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-27 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphinxsite', '0003_auto_20180226_0117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitecode',
            old_name='used',
            new_name='in_use',
        ),
        migrations.AddField(
            model_name='invitecode',
            name='send_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='code',
            field=models.CharField(max_length=64),
        ),
    ]
