# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-27 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphinxsite', '0004_auto_20180227_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='team',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
