# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-28 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sphinxsite', '0006_auto_20180227_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='invite_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='siteuser_invitecode', to='sphinxsite.InviteCode'),
        ),
    ]
